[platformio]
src_dir = src/esp32-c3
core_dir = C:/.pio

[env:esp32-c3]
platform = espressif32@6.10.0
board = esp32-c3-devkitm-1
framework = arduino

platform_packages =
  framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

build_flags =
  -std=gnu++17
build_unflags =
  -std=gnu++11

monitor_speed = 115200
upload_speed = 115200